name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install git-lfs (optional but prevents some HF LFS hook issues)
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install --local || true

      - name: Configure git user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Remove existing 'space' remote if present (safe)
          git remote remove space 2>/dev/null || true

          # NOTE: token is injected from GitHub secrets; GitHub masks secrets in logs.
          # Add remote with token for HTTPS authentication
          git remote add space https://Yomex139:${HF_TOKEN}@huggingface.co/spaces/Yomex139/LuminaAI-app

          # Force push main branch to the HF Space
          git push --force space main
