name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ "main" ]   # Change if your main branch is "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Push to Hugging Face Space
        uses: huggingface/hub-actions@v1
        with:
          repo-token: ${{ secrets.HF_TOKEN }}
          repo-id: Yomex139/LuminaAI-app
