name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ "main" ]   # change if your branch is "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          huggingface-cli login --token $HF_TOKEN
          huggingface-cli repo create quantumyomi-chatbot --type space --sdk gradio --yes --token $HF_TOKEN || true
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git remote add space https://huggingface.co/spaces/Yomex139/LuminaAI-app
          git push space main --force
