name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main   # deploys only when you push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Hugging Face Hub
        run: pip install huggingface_hub --upgrade

      - name: Login to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          hf auth login --token $HF_TOKEN --add-to-git-credential

      - name: Push to Hugging Face Space
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add space https://huggingface.co/spaces/Yomex139/LuminaAI-app
          git push --force space main
